artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Kushal19903/Branching-tutorial/raw/refs/heads/main/winequality-red.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


#after data ingestion create file in research folder as 02_data_validation
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv  #path for winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt        #return true or false of status 
